server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html; # SPA Serving trick. If neither works, fall back to index.html.
    }

    location = /index.html {
        add_header Cache-Control "no-cache";
    }
}
